name: 'Fast Telegram Action'
description: 'Sends a message to Telegram using a Bash script'
author: 's00d'
branding:
  icon: 'message-square'
  color: 'purple'

inputs:
  token:
    description: 'Telegram Bot API token'
    required: true
  to:
    description: 'Telegram chat ID or group ID'
    required: true
  message:
    description: 'Message text (supports Markdown)'
    required: true
    default: 'Hello from GitHub Actions!'
  format:
    description: 'markdown or html'
    required: false
    default: 'markdown'
  disable_web_page_preview: # Add the disable-web-page-preview input
    description: 'Disable web page preview in the Telegram message (set to "True" to disable)'
    required: false
  photo:
    description: 'Photo message'
    required: false
  document:
    description: 'Document message'
    required: false
  sticker:
    description: 'Sticker message'
    required: false
  audio:
    description: 'Audio message'
    required: false
  voice:
    description: 'Voice message'
    required: false
  location:
    description: 'Location message'
    required: false
  venue:
    description: 'Venue message'
    required: false
  video:
    description: 'Video message'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Send Telegram message
      shell: bash
      env:
        TELEGRAM_TOKEN: ${{ inputs.token }}
        TELEGRAM_TO: ${{ inputs.to }}
        MESSAGE_TEXT: ${{ inputs.message }}
        DISABLE_WEB_PAGE_PREVIEW: ${{ inputs.disable_web_page_preview }}
        PARSE_MODE: ${{ env.format }}
        PHOTO: ${{ inputs.photo }}
        DOCUMENT: ${{ inputs.document }}
        STICKER: ${{ inputs.sticker }}
        AUDIO: ${{ inputs.audio }}
        VOICE: ${{ inputs.voice }}
        VIDEO: ${{ inputs.video }}
      run: |
        curl -s -X POST https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage \
          -d chat_id=${TELEGRAM_TO} \
          -d text="${MESSAGE_TEXT}" \
          -d parse_mode=${PARSE_MODE} \
          -d disable_web_page_preview=${DISABLE_WEB_PAGE_PREVIEW} \
          ${SOCKS5:+-x ${SOCKS5}} \
          ${PHOTO:+-F photo="@${PHOTO}"} \
          ${DOCUMENT:+-F document="@${DOCUMENT}"} \
          ${STICKER:+-F sticker="@${STICKER}"} \
          ${AUDIO:+-F audio="@${AUDIO}"} \
          ${VOICE:+-F voice="@${VOICE}"} \
          ${VIDEO:+-F video="@${VIDEO}"}
