name: Send Telegram Message

on:
  push:
    branches:
      - main

jobs:
  send-message:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Message
        uses: s00d/fast-telegram-action@v2
        with:
          token: ${{ secrets.TELEGRAM_TOKEN }}
          to: ${{ secrets.TELEGRAM_TO }}
          message: 'This is a test message from GitHub Actions!'
