name: Send Telegram Message

on:
  push:
    branches:
      - main

jobs:
  send-message:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Message
        uses: s00d/fast-telegram-action@v4
        with:
          token: ${{ secrets.TELEGRAM_TOKEN }}
          to: ${{ secrets.TELEGRAM_TO }}
          message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}

            Repository: ${{ github.repository }}

            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
          photo: 'https://github.com/s00d/fast-telegram-action/blob/main/tests/github.png?raw=true'
          format: markdown
          disable_web_page_preview: "True"
